### PR TITLE
[MRAR-90] Upgrade parent POM to version 41

### PR DESCRIPTION
**Pull request by CrazyHZM**
The reason for this https://github.com/apache/maven-rar-plugin/pull/9  failure is that there is no formatting.

### CODE REVIEW

**Comment by slachiewicz** [comment]
Thank you for Your time. I already prepared changes

**Comment by CrazyHZM** [comment]
> Thank you for Your time. I already prepared changes

If you have already made changes, you are free to turn off my pr :)

**Review by slachiewicz — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #44

**Comment by jira-importer** [comment]
Resolve #44

**Pull request merged**
